security:
  require-ssl:true
server:
  port: 8443
  ssl:
    key-store: classpath:saml/keystore.p12
    key-store-password: secret
    keyStoreType: PKCS12
    keyAlias: tomcat
  servlet:
    context-path: /
# server:
#     port: 443
#     ssl:
#       enabled: true
#       key-alias: clmkey
#       key-store: classpath:saml/keystore.jks
#       key-store-password: secret


spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:templates/
    suffix: .html
  security:
    saml2:
      network:
        read-timeout: 10000
        connect-timeout: 5000
      # relyingparty:
      #   registration:
      #     ClmTest:
      #       entity-id: cfaeb052-fbf1-4203-93eb-714a868ed88d
      #       tenant-id: b46c8501-fe2f-4e49-98a9-6a8a811e4f39
      #       identityprovider:
      #         entity-id: "https://login.microsoftonline.com/b46c8501-fe2f-4e49-98a9-6a8a811e4f39/metadata"
      #       assertingparty:
      #         consumer-service-url: "https://localhost:8443/logged-in"
      #         metadata-uri: "classpath:metadata/azure-idp.xml"
      service-provider:
        entity-id: ClmTest
        alias: ClmTest  
        sign-metadata: false
        sign-requests: false
        want-assertions-signed: true
        single-logout-enabled: true
        encrypt-assertions: false
        acs:
          location: https://localhost:8443/
        name-ids:
          - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
          - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
        keys:
          active:
            name: sp-signing-key-1
        providers:
            alias: ClmTest
            metadata: https://login.microsoftonline.com/b46c8501-fe2f-4e49-98a9-6a8a811e4f39/federationmetadata/2007-06/federationmetadata.xml?appid=cfaeb052-fbf1-4203-93eb-714a868ed88d
            skip-ssl-validation: true
            link-text: enter-into-ClmTest
            authentication-request-binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
            single-logout-url: https://login.microsoftonline.com/b46c8501-fe2f-4e49-98a9-6a8a811e4f39/saml2